create table FILES 
(
	DOCID UNIQUEIDENTIFIER NOT NULL ROWGUIDCOL UNIQUE DEFAULT NEWID(),
	DOC VARBINARY(MAX) NULL
)

DECLARE @DOC AS VARBINARY(MAX)
SELECT @DOC = CAST (BULKCOLUMN AS VARBINARY(MAX))
FROM OPENROWSET (BULK 'C:\FILES\TEST.TXT', SINGLE_BLOB) AS DOC

INSERT INTO FILES (DOC)
VALUES(@DOC)

SELECT * FROM FILES
SELECT DOC.PathName() from files

